config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'site#home'
  get '/contact', to: 'site#contact'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/say_name/:name', to: 'site#say_name'
  get '/calculator', to: 'site#calculator'
  post '/calculate', to: 'site#calculate'
  get '/projects', to: 'projects#index'
  get '/projects/new', to: 'projects#new'
  get 'projects/:id', to: 'projects#show'

  post '/projects', to: 'projects#create'

  get '/projects/:project_id/time_entries', to: 'time_entries#index'

  get '/projects/:project_id/time_entries/new', to: 'time_entries#new'
  post '/projects/:project_id/time_entries', to: 'time_entries#create', as: :project_time_entries

  get '/projects/:project_id/time_entries/:id/edit', to: 'time_entries#edit', as: :project_time_entry_edit
  patch 'projects/:project_id/time_entries/:id', to: 'time_entries#update', as: :project_time_entry
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :time_entries

  validates :name, presence: true,
                   uniqueness: true,
                   length: { maximum: 30 }
                  #  format: { with: /\[a-zA-Z\s]/}
  #
  # validates_associated :time_entries

  def self.clean_old
    old_projects= Project.where("created_at <?", 1.week.ago)
    old_projects.destroy_all
  end

  #to check for errors varible.errors.full_messages
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project
  validates :hours, presence: true, numericality:  true
  validates :minutes, presence: true, numericality: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(created_at: :desc).limit(10)
  end
  def show
    @my_project= Project.find_by(id: params[:id])

    unless @my_project
      render "no_projects_found"
    end
  end

  def new
    @my_project= Project.new
  end

  def create
    @my_project = Project.new(name: params[:project][:name],
                              description: params[:project][:description])
   @my_project.save
  redirect_to "/projects/#{@my_project.id}"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def say_name
    @name= params[:name]
    render 'say_name'
  end

  def home
  end

  def controler
    render 'contact', layout: 'admin'
  end

  def calculator
    render 'calculator'
  end

  def calculate
    params[:first_num]
    params[:second_num]
    @result = params[:first_num].to_i + params[:second_num].to_i
    render 'calculate'
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @time_entries = @project.time_entries#.where("date >?", 1.month.ago)
  end

  def new
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.new
  end

  def create
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.create(entry_params)
    if @my_entry
      redirect_to action: 'index',
      controller: "time_entries",
      project_id: @my_project.id
    else
      render "new"
    end
  end

  def edit
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.find(params[:id])
  end

  def update
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.find(params[:id])

    if @my_entry.update(entry_params)
      redirect_to action:"index",
                  controller: "time_entries",
                  project_id: @my_project.id

    else
      render "edit"
    end
  end

  private
  def entry_params
    params.require(:time_entry).permit(:hours, :minutes, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Admin area</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project|%>
    <li> <%= "#{project.name} - #{project.description}" %> </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>Add a project</h1>

<%= form_for @my_project do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>

<%=f.label :description%>
<%=f.text_area :description%>
<%=f.button "submit me"%>

<% end %>

app/views/projects/no_projects_found.html.erb
sorry, there is not such projects

app/views/projects/show.html.erb
<p> <%=@my_project.name%> </p>
-
<p> <%=@my_project.description%> </p>

app/views/site/calculate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <p>

    The result is equal to <%=@result%> </p>
  </body>
</html>

app/views/site/calculator.html.erb
<form class="calculate" action="/calculate" method="post">
  <input type="text" name="first_num" placeholder="First Number">
  <input type="text" name="second_num" placeholder="Second Number">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button type="submit">Add</button>
</form>

app/views/site/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>contact@ironhack.com</h1>
  </body>
</html>

app/views/site/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>HELLO WORLD!!!</h1>
    <%=image_tag "dramatic_glasses.gif" %>
    <%=link_to 'take me to calculator', calculator_path, class: "text" %>
  </body>
</html>

app/views/site/say_name.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Hello <%=@name%></h1>
  </body>
</html>

app/views/time_entries/_form.html.erb
<%= form_for [@my_project, @my_entry] do |f| %>
  <%= f.label :hours%>
  <%= f.text_field :hours%>
  <br>
  <%= f.label :minutes%>
  <%= f.text_field :minutes%>
  <br>
  <%= f.label :date%>
  <%= f.date_field :date%>
  <br>
  <%= f.label :comments%>
  <%= f.date_field :comments%>

  <%= f.submit "save"%>


<%end%>

app/views/time_entries/edit.html.erb
<%=render "form"%>

app/views/time_entries/index.html.erb
<h1><%=@project.name%></h1>
<ul>

  <%@time_entries.each do |time_entry| %>
  <li>
    <p> hours: <%=time_entry.hours%> : <%=time_entry.minutes %> -
    <%=time_entry.comments%>
    <%=link_to "edit", project_time_entry_edit_path(@project, time_entry)%>
  </li>
  <%end%>
</ul>

app/views/time_entries/new.html.erb
<%= form_for [@my_project, @my_entry] do |f| %>
  <%= f.label :hours%>
  <%= f.text_field :hours%>
  <br>
  <%= f.label :minutes%>
  <%= f.text_field :minutes%>
  <br>
  <%= f.label :date%>
  <%= f.date_field :date%>

  <%= f.submit "save"%>

<%end%>